// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pooled connection for runtime queries (port 6543)
    url: process.env["DATABASE_URL"],
    // Direct connection for migrations/db push (port 5432)
    directUrl: process.env["DIRECT_URL"],
  } as any,
});
