import { NextRequest, NextResponse } from "next/server";
import { calendarMonitor } from "@/lib/agents/CalendarMonitor";
import { judgmentAgent } from "@/lib/agents/JudgmentAgent";
import { briefingGenerator } from "@/lib/agents/BriefingGenerator";
import { createEmptySituationContext } from "@/lib/types/situationContext";

// This endpoint generates a demo briefing for testing
// In production, briefings would be generated by cron jobs

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { parentProfile } = body;

    if (!parentProfile || !parentProfile.name || !parentProfile.age) {
      return NextResponse.json(
        { error: "Parent profile with name and age is required" },
        { status: 400 }
      );
    }

    console.log("🧪 [Demo] Generating briefing for:", parentProfile.name);

    // 1. Create situation context from parent profile
    const parentId = parentProfile.id || `parent_${Date.now()}`;
    const context = createEmptySituationContext(
      parentId,
      parentProfile.name,
      parentProfile.age,
      parentProfile.state || "Unknown"
    );

    // Add date of birth for calendar monitoring (estimate from age)
    const today = new Date();
    const birthYear = today.getFullYear() - parentProfile.age;
    context.profile.dateOfBirth = `${birthYear}-${String(today.getMonth() + 1).padStart(2, "0")}-${String(today.getDate()).padStart(2, "0")}`;

    // Add some demo data to make briefing more interesting
    context.medical.insurance = {
      provider: "Medicare Part D",
      policyNumber: "DEMO-12345",
      coverageType: "medicare",
    };

    console.log("📋 [Demo] Created situation context");

    // 2. Run Calendar Monitor
    const signals = await calendarMonitor.run(parentId, context);
    console.log(`🔍 [Demo] Calendar Monitor found ${signals.length} signals`);

    if (signals.length === 0) {
      return NextResponse.json({
        message: "No signals detected - try adjusting parent's age or date of birth",
        signals: [],
      });
    }

    // 3. Score signals with Judgment Agent
    const scoredSignals = await judgmentAgent.scoreSignals(signals, context);
    console.log(`⚖️ [Demo] Scored ${scoredSignals.length} signals`);

    // Filter to high-relevance signals (score >= 70)
    const highRelevanceSignals = scoredSignals.filter((s) => s.relevanceScore >= 70);
    console.log(`✅ [Demo] ${highRelevanceSignals.length} high-relevance signals`);

    if (highRelevanceSignals.length === 0) {
      return NextResponse.json({
        message: "No high-relevance signals found",
        signals: scoredSignals.map((s) => ({
          title: s.title,
          score: s.relevanceScore,
        })),
      });
    }

    // 4. Generate briefing
    const briefing = await briefingGenerator.generateBriefing(
      highRelevanceSignals,
      context
    );
    console.log(`📄 [Demo] Generated briefing:`, briefing.briefingId);

    // 5. Return briefing (client will save to localStorage)
    return NextResponse.json({
      message: "Demo briefing generated successfully",
      briefing,
      signals: scoredSignals.map((s) => ({
        title: s.title,
        score: s.relevanceScore,
        priority: s.priority,
      })),
    });
  } catch (error) {
    console.error("❌ [Demo] Error:", error);
    return NextResponse.json(
      {
        error: "Failed to generate demo briefing",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
